language: generic
sudo: required
services:
  - docker

befor install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  -docker run react-test npm test -- --coverage

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker
  #Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take this images and push them to docker-hub
  - docker push multi-client
  - docker push multi-nginx
  - docker push multi-server
  - docker push multi-worker
